/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as AkteRouteImport } from './routes/akte'
import { Route as AnbieterRouteImport } from './routes/anbieter'
import { Route as AssistentRouteImport } from './routes/assistent'
import { Route as BestaetigenRouteImport } from './routes/bestaetigen'
import { Route as CheckRouteImport } from './routes/check'
import { Route as ComplianceRouteImport } from './routes/compliance'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as EinwilligungenRouteImport } from './routes/einwilligungen'
import { Route as ErgebnisRouteImport } from './routes/ergebnis'
import { Route as ErgebnisseRouteImport } from './routes/ergebnisse'
import { Route as ErinnerungenRouteImport } from './routes/erinnerungen'
import { Route as HinweiseRouteImport } from './routes/hinweise'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as InstallierenRouteImport } from './routes/installieren'
import { Route as KaeufeRouteImport } from './routes/kaeufe'
import { Route as KoerperRouteImport } from './routes/koerper'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MehrRouteImport } from './routes/mehr'
import { Route as PlanerRouteImport } from './routes/planer'
import { Route as PraxisRouteImport } from './routes/praxis'
import { Route as PreiseRouteImport } from './routes/preise'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PruefungRouteImport } from './routes/pruefung'
import { Route as RisikenRouteImport } from './routes/risiken'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as VorschauRouteImport } from './routes/vorschau'
import { Route as WiderrufRouteImport } from './routes/widerruf'
import { Route as WissenRouteImport } from './routes/wissen'
import { Route as ZahlungRouteImport } from './routes/zahlung'
import { Route as AkteIndexRouteImport } from './routes/akte.index'
import { Route as AkteIdRouteImport } from './routes/akte.$id'
import { Route as AnbieterIndexRouteImport } from './routes/anbieter.index'
import { Route as AnbieterSlugRouteImport } from './routes/anbieter.$slug'
import { Route as ErgebnisseIndexRouteImport } from './routes/ergebnisse.index'
import { Route as ErgebnisseIdRouteImport } from './routes/ergebnisse.$id'
import { Route as ErgebnisseMeineRouteImport } from './routes/ergebnisse.meine'
import { Route as ErgebnisseTeilenRouteImport } from './routes/ergebnisse.teilen'
import { Route as ProAbbruchRouteImport } from './routes/pro.abbruch'
import { Route as ProErfolgRouteImport } from './routes/pro.erfolg'
import { Route as WissenIndexRouteImport } from './routes/wissen.index'
import { Route as WissenSlugRouteImport } from './routes/wissen.$slug'
import { Route as ZahlungIndexRouteImport } from './routes/zahlung.index'
import { Route as ZahlungIdRouteImport } from './routes/zahlung.$id'
import { Route as ZahlungAbbruchRouteImport } from './routes/zahlung.abbruch'
import { Route as ZahlungErfolgRouteImport } from './routes/zahlung.erfolg'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiStripeWebhookRouteImport } from './routes/api.stripe.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const AkteRoute = AkteRouteImport.update({
  id: '/akte',
  path: '/akte',
  getParentRoute: () => rootRouteImport,
} as any)
const AnbieterRoute = AnbieterRouteImport.update({
  id: '/anbieter',
  path: '/anbieter',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistentRoute = AssistentRouteImport.update({
  id: '/assistent',
  path: '/assistent',
  getParentRoute: () => rootRouteImport,
} as any)
const BestaetigenRoute = BestaetigenRouteImport.update({
  id: '/bestaetigen',
  path: '/bestaetigen',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckRoute = CheckRouteImport.update({
  id: '/check',
  path: '/check',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceRoute = ComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const EinwilligungenRoute = EinwilligungenRouteImport.update({
  id: '/einwilligungen',
  path: '/einwilligungen',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgebnisRoute = ErgebnisRouteImport.update({
  id: '/ergebnis',
  path: '/ergebnis',
  getParentRoute: () => rootRouteImport,
} as any)
const ErgebnisseRoute = ErgebnisseRouteImport.update({
  id: '/ergebnisse',
  path: '/ergebnisse',
  getParentRoute: () => rootRouteImport,
} as any)
const ErinnerungenRoute = ErinnerungenRouteImport.update({
  id: '/erinnerungen',
  path: '/erinnerungen',
  getParentRoute: () => rootRouteImport,
} as any)
const HinweiseRoute = HinweiseRouteImport.update({
  id: '/hinweise',
  path: '/hinweise',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const InstallierenRoute = InstallierenRouteImport.update({
  id: '/installieren',
  path: '/installieren',
  getParentRoute: () => rootRouteImport,
} as any)
const KaeufeRoute = KaeufeRouteImport.update({
  id: '/kaeufe',
  path: '/kaeufe',
  getParentRoute: () => rootRouteImport,
} as any)
const KoerperRoute = KoerperRouteImport.update({
  id: '/koerper',
  path: '/koerper',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MehrRoute = MehrRouteImport.update({
  id: '/mehr',
  path: '/mehr',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanerRoute = PlanerRouteImport.update({
  id: '/planer',
  path: '/planer',
  getParentRoute: () => rootRouteImport,
} as any)
const PraxisRoute = PraxisRouteImport.update({
  id: '/praxis',
  path: '/praxis',
  getParentRoute: () => rootRouteImport,
} as any)
const PreiseRoute = PreiseRouteImport.update({
  id: '/preise',
  path: '/preise',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PruefungRoute = PruefungRouteImport.update({
  id: '/pruefung',
  path: '/pruefung',
  getParentRoute: () => rootRouteImport,
} as any)
const RisikenRoute = RisikenRouteImport.update({
  id: '/risiken',
  path: '/risiken',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const VorschauRoute = VorschauRouteImport.update({
  id: '/vorschau',
  path: '/vorschau',
  getParentRoute: () => rootRouteImport,
} as any)
const WiderrufRoute = WiderrufRouteImport.update({
  id: '/widerruf',
  path: '/widerruf',
  getParentRoute: () => rootRouteImport,
} as any)
const WissenRoute = WissenRouteImport.update({
  id: '/wissen',
  path: '/wissen',
  getParentRoute: () => rootRouteImport,
} as any)
const ZahlungRoute = ZahlungRouteImport.update({
  id: '/zahlung',
  path: '/zahlung',
  getParentRoute: () => rootRouteImport,
} as any)
const AkteIndexRoute = AkteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AkteRoute,
} as any)
const AkteIdRoute = AkteIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AkteRoute,
} as any)
const AnbieterIndexRoute = AnbieterIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnbieterRoute,
} as any)
const AnbieterSlugRoute = AnbieterSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AnbieterRoute,
} as any)
const ErgebnisseIndexRoute = ErgebnisseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ErgebnisseRoute,
} as any)
const ErgebnisseIdRoute = ErgebnisseIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ErgebnisseRoute,
} as any)
const ErgebnisseMeineRoute = ErgebnisseMeineRouteImport.update({
  id: '/meine',
  path: '/meine',
  getParentRoute: () => ErgebnisseRoute,
} as any)
const ErgebnisseTeilenRoute = ErgebnisseTeilenRouteImport.update({
  id: '/teilen',
  path: '/teilen',
  getParentRoute: () => ErgebnisseRoute,
} as any)
const ProAbbruchRoute = ProAbbruchRouteImport.update({
  id: '/abbruch',
  path: '/abbruch',
  getParentRoute: () => ProRoute,
} as any)
const ProErfolgRoute = ProErfolgRouteImport.update({
  id: '/erfolg',
  path: '/erfolg',
  getParentRoute: () => ProRoute,
} as any)
const WissenIndexRoute = WissenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WissenRoute,
} as any)
const WissenSlugRoute = WissenSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WissenRoute,
} as any)
const ZahlungIndexRoute = ZahlungIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ZahlungRoute,
} as any)
const ZahlungIdRoute = ZahlungIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ZahlungRoute,
} as any)
const ZahlungAbbruchRoute = ZahlungAbbruchRouteImport.update({
  id: '/abbruch',
  path: '/abbruch',
  getParentRoute: () => ZahlungRoute,
} as any)
const ZahlungErfolgRoute = ZahlungErfolgRouteImport.update({
  id: '/erfolg',
  path: '/erfolg',
  getParentRoute: () => ZahlungRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStripeWebhookRoute = ApiStripeWebhookRouteImport.update({
  id: '/api/stripe/webhook',
  path: '/api/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/akte': typeof AkteRouteWithChildren
  '/anbieter': typeof AnbieterRouteWithChildren
  '/assistent': typeof AssistentRoute
  '/bestaetigen': typeof BestaetigenRoute
  '/check': typeof CheckRoute
  '/compliance': typeof ComplianceRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einwilligungen': typeof EinwilligungenRoute
  '/ergebnis': typeof ErgebnisRoute
  '/ergebnisse': typeof ErgebnisseRouteWithChildren
  '/erinnerungen': typeof ErinnerungenRoute
  '/hinweise': typeof HinweiseRoute
  '/impressum': typeof ImpressumRoute
  '/installieren': typeof InstallierenRoute
  '/kaeufe': typeof KaeufeRoute
  '/koerper': typeof KoerperRoute
  '/login': typeof LoginRoute
  '/mehr': typeof MehrRoute
  '/planer': typeof PlanerRoute
  '/praxis': typeof PraxisRoute
  '/preise': typeof PreiseRoute
  '/pro': typeof ProRouteWithChildren
  '/pruefung': typeof PruefungRoute
  '/risiken': typeof RisikenRoute
  '/scanner': typeof ScannerRoute
  '/vorschau': typeof VorschauRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/zahlung': typeof ZahlungRouteWithChildren
  '/akte/$id': typeof AkteIdRoute
  '/anbieter/$slug': typeof AnbieterSlugRoute
  '/ergebnisse/$id': typeof ErgebnisseIdRoute
  '/ergebnisse/meine': typeof ErgebnisseMeineRoute
  '/ergebnisse/teilen': typeof ErgebnisseTeilenRoute
  '/pro/abbruch': typeof ProAbbruchRoute
  '/pro/erfolg': typeof ProErfolgRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/zahlung/$id': typeof ZahlungIdRoute
  '/zahlung/abbruch': typeof ZahlungAbbruchRoute
  '/zahlung/erfolg': typeof ZahlungErfolgRoute
  '/akte/': typeof AkteIndexRoute
  '/anbieter/': typeof AnbieterIndexRoute
  '/ergebnisse/': typeof ErgebnisseIndexRoute
  '/wissen/': typeof WissenIndexRoute
  '/zahlung/': typeof ZahlungIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/assistent': typeof AssistentRoute
  '/bestaetigen': typeof BestaetigenRoute
  '/check': typeof CheckRoute
  '/compliance': typeof ComplianceRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einwilligungen': typeof EinwilligungenRoute
  '/ergebnis': typeof ErgebnisRoute
  '/erinnerungen': typeof ErinnerungenRoute
  '/hinweise': typeof HinweiseRoute
  '/impressum': typeof ImpressumRoute
  '/installieren': typeof InstallierenRoute
  '/kaeufe': typeof KaeufeRoute
  '/koerper': typeof KoerperRoute
  '/login': typeof LoginRoute
  '/mehr': typeof MehrRoute
  '/planer': typeof PlanerRoute
  '/praxis': typeof PraxisRoute
  '/preise': typeof PreiseRoute
  '/pro': typeof ProRouteWithChildren
  '/pruefung': typeof PruefungRoute
  '/risiken': typeof RisikenRoute
  '/scanner': typeof ScannerRoute
  '/vorschau': typeof VorschauRoute
  '/widerruf': typeof WiderrufRoute
  '/akte/$id': typeof AkteIdRoute
  '/anbieter/$slug': typeof AnbieterSlugRoute
  '/ergebnisse/$id': typeof ErgebnisseIdRoute
  '/ergebnisse/meine': typeof ErgebnisseMeineRoute
  '/ergebnisse/teilen': typeof ErgebnisseTeilenRoute
  '/pro/abbruch': typeof ProAbbruchRoute
  '/pro/erfolg': typeof ProErfolgRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/zahlung/$id': typeof ZahlungIdRoute
  '/zahlung/abbruch': typeof ZahlungAbbruchRoute
  '/zahlung/erfolg': typeof ZahlungErfolgRoute
  '/akte': typeof AkteIndexRoute
  '/anbieter': typeof AnbieterIndexRoute
  '/ergebnisse': typeof ErgebnisseIndexRoute
  '/wissen': typeof WissenIndexRoute
  '/zahlung': typeof ZahlungIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/akte': typeof AkteRouteWithChildren
  '/anbieter': typeof AnbieterRouteWithChildren
  '/assistent': typeof AssistentRoute
  '/bestaetigen': typeof BestaetigenRoute
  '/check': typeof CheckRoute
  '/compliance': typeof ComplianceRoute
  '/datenschutz': typeof DatenschutzRoute
  '/einwilligungen': typeof EinwilligungenRoute
  '/ergebnis': typeof ErgebnisRoute
  '/ergebnisse': typeof ErgebnisseRouteWithChildren
  '/erinnerungen': typeof ErinnerungenRoute
  '/hinweise': typeof HinweiseRoute
  '/impressum': typeof ImpressumRoute
  '/installieren': typeof InstallierenRoute
  '/kaeufe': typeof KaeufeRoute
  '/koerper': typeof KoerperRoute
  '/login': typeof LoginRoute
  '/mehr': typeof MehrRoute
  '/planer': typeof PlanerRoute
  '/praxis': typeof PraxisRoute
  '/preise': typeof PreiseRoute
  '/pro': typeof ProRouteWithChildren
  '/pruefung': typeof PruefungRoute
  '/risiken': typeof RisikenRoute
  '/scanner': typeof ScannerRoute
  '/vorschau': typeof VorschauRoute
  '/widerruf': typeof WiderrufRoute
  '/wissen': typeof WissenRouteWithChildren
  '/zahlung': typeof ZahlungRouteWithChildren
  '/akte/$id': typeof AkteIdRoute
  '/anbieter/$slug': typeof AnbieterSlugRoute
  '/ergebnisse/$id': typeof ErgebnisseIdRoute
  '/ergebnisse/meine': typeof ErgebnisseMeineRoute
  '/ergebnisse/teilen': typeof ErgebnisseTeilenRoute
  '/pro/abbruch': typeof ProAbbruchRoute
  '/pro/erfolg': typeof ProErfolgRoute
  '/wissen/$slug': typeof WissenSlugRoute
  '/zahlung/$id': typeof ZahlungIdRoute
  '/zahlung/abbruch': typeof ZahlungAbbruchRoute
  '/zahlung/erfolg': typeof ZahlungErfolgRoute
  '/akte/': typeof AkteIndexRoute
  '/anbieter/': typeof AnbieterIndexRoute
  '/ergebnisse/': typeof ErgebnisseIndexRoute
  '/wissen/': typeof WissenIndexRoute
  '/zahlung/': typeof ZahlungIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/stripe/webhook': typeof ApiStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/akte'
    | '/anbieter'
    | '/assistent'
    | '/bestaetigen'
    | '/check'
    | '/compliance'
    | '/datenschutz'
    | '/einwilligungen'
    | '/ergebnis'
    | '/ergebnisse'
    | '/erinnerungen'
    | '/hinweise'
    | '/impressum'
    | '/installieren'
    | '/kaeufe'
    | '/koerper'
    | '/login'
    | '/mehr'
    | '/planer'
    | '/praxis'
    | '/preise'
    | '/pro'
    | '/pruefung'
    | '/risiken'
    | '/scanner'
    | '/vorschau'
    | '/widerruf'
    | '/wissen'
    | '/zahlung'
    | '/akte/$id'
    | '/anbieter/$slug'
    | '/ergebnisse/$id'
    | '/ergebnisse/meine'
    | '/ergebnisse/teilen'
    | '/pro/abbruch'
    | '/pro/erfolg'
    | '/wissen/$slug'
    | '/zahlung/$id'
    | '/zahlung/abbruch'
    | '/zahlung/erfolg'
    | '/akte/'
    | '/anbieter/'
    | '/ergebnisse/'
    | '/wissen/'
    | '/zahlung/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/assistent'
    | '/bestaetigen'
    | '/check'
    | '/compliance'
    | '/datenschutz'
    | '/einwilligungen'
    | '/ergebnis'
    | '/erinnerungen'
    | '/hinweise'
    | '/impressum'
    | '/installieren'
    | '/kaeufe'
    | '/koerper'
    | '/login'
    | '/mehr'
    | '/planer'
    | '/praxis'
    | '/preise'
    | '/pro'
    | '/pruefung'
    | '/risiken'
    | '/scanner'
    | '/vorschau'
    | '/widerruf'
    | '/akte/$id'
    | '/anbieter/$slug'
    | '/ergebnisse/$id'
    | '/ergebnisse/meine'
    | '/ergebnisse/teilen'
    | '/pro/abbruch'
    | '/pro/erfolg'
    | '/wissen/$slug'
    | '/zahlung/$id'
    | '/zahlung/abbruch'
    | '/zahlung/erfolg'
    | '/akte'
    | '/anbieter'
    | '/ergebnisse'
    | '/wissen'
    | '/zahlung'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/akte'
    | '/anbieter'
    | '/assistent'
    | '/bestaetigen'
    | '/check'
    | '/compliance'
    | '/datenschutz'
    | '/einwilligungen'
    | '/ergebnis'
    | '/ergebnisse'
    | '/erinnerungen'
    | '/hinweise'
    | '/impressum'
    | '/installieren'
    | '/kaeufe'
    | '/koerper'
    | '/login'
    | '/mehr'
    | '/planer'
    | '/praxis'
    | '/preise'
    | '/pro'
    | '/pruefung'
    | '/risiken'
    | '/scanner'
    | '/vorschau'
    | '/widerruf'
    | '/wissen'
    | '/zahlung'
    | '/akte/$id'
    | '/anbieter/$slug'
    | '/ergebnisse/$id'
    | '/ergebnisse/meine'
    | '/ergebnisse/teilen'
    | '/pro/abbruch'
    | '/pro/erfolg'
    | '/wissen/$slug'
    | '/zahlung/$id'
    | '/zahlung/abbruch'
    | '/zahlung/erfolg'
    | '/akte/'
    | '/anbieter/'
    | '/ergebnisse/'
    | '/wissen/'
    | '/zahlung/'
    | '/api/auth/$'
    | '/api/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  AkteRoute: typeof AkteRouteWithChildren
  AnbieterRoute: typeof AnbieterRouteWithChildren
  AssistentRoute: typeof AssistentRoute
  BestaetigenRoute: typeof BestaetigenRoute
  CheckRoute: typeof CheckRoute
  ComplianceRoute: typeof ComplianceRoute
  DatenschutzRoute: typeof DatenschutzRoute
  EinwilligungenRoute: typeof EinwilligungenRoute
  ErgebnisRoute: typeof ErgebnisRoute
  ErgebnisseRoute: typeof ErgebnisseRouteWithChildren
  ErinnerungenRoute: typeof ErinnerungenRoute
  HinweiseRoute: typeof HinweiseRoute
  ImpressumRoute: typeof ImpressumRoute
  InstallierenRoute: typeof InstallierenRoute
  KaeufeRoute: typeof KaeufeRoute
  KoerperRoute: typeof KoerperRoute
  LoginRoute: typeof LoginRoute
  MehrRoute: typeof MehrRoute
  PlanerRoute: typeof PlanerRoute
  PraxisRoute: typeof PraxisRoute
  PreiseRoute: typeof PreiseRoute
  ProRoute: typeof ProRouteWithChildren
  PruefungRoute: typeof PruefungRoute
  RisikenRoute: typeof RisikenRoute
  ScannerRoute: typeof ScannerRoute
  VorschauRoute: typeof VorschauRoute
  WiderrufRoute: typeof WiderrufRoute
  WissenRoute: typeof WissenRouteWithChildren
  ZahlungRoute: typeof ZahlungRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiStripeWebhookRoute: typeof ApiStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akte': {
      id: '/akte'
      path: '/akte'
      fullPath: '/akte'
      preLoaderRoute: typeof AkteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anbieter': {
      id: '/anbieter'
      path: '/anbieter'
      fullPath: '/anbieter'
      preLoaderRoute: typeof AnbieterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistent': {
      id: '/assistent'
      path: '/assistent'
      fullPath: '/assistent'
      preLoaderRoute: typeof AssistentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bestaetigen': {
      id: '/bestaetigen'
      path: '/bestaetigen'
      fullPath: '/bestaetigen'
      preLoaderRoute: typeof BestaetigenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check': {
      id: '/check'
      path: '/check'
      fullPath: '/check'
      preLoaderRoute: typeof CheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance': {
      id: '/compliance'
      path: '/compliance'
      fullPath: '/compliance'
      preLoaderRoute: typeof ComplianceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/einwilligungen': {
      id: '/einwilligungen'
      path: '/einwilligungen'
      fullPath: '/einwilligungen'
      preLoaderRoute: typeof EinwilligungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ergebnis': {
      id: '/ergebnis'
      path: '/ergebnis'
      fullPath: '/ergebnis'
      preLoaderRoute: typeof ErgebnisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ergebnisse': {
      id: '/ergebnisse'
      path: '/ergebnisse'
      fullPath: '/ergebnisse'
      preLoaderRoute: typeof ErgebnisseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/erinnerungen': {
      id: '/erinnerungen'
      path: '/erinnerungen'
      fullPath: '/erinnerungen'
      preLoaderRoute: typeof ErinnerungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hinweise': {
      id: '/hinweise'
      path: '/hinweise'
      fullPath: '/hinweise'
      preLoaderRoute: typeof HinweiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/installieren': {
      id: '/installieren'
      path: '/installieren'
      fullPath: '/installieren'
      preLoaderRoute: typeof InstallierenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kaeufe': {
      id: '/kaeufe'
      path: '/kaeufe'
      fullPath: '/kaeufe'
      preLoaderRoute: typeof KaeufeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/koerper': {
      id: '/koerper'
      path: '/koerper'
      fullPath: '/koerper'
      preLoaderRoute: typeof KoerperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mehr': {
      id: '/mehr'
      path: '/mehr'
      fullPath: '/mehr'
      preLoaderRoute: typeof MehrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planer': {
      id: '/planer'
      path: '/planer'
      fullPath: '/planer'
      preLoaderRoute: typeof PlanerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/praxis': {
      id: '/praxis'
      path: '/praxis'
      fullPath: '/praxis'
      preLoaderRoute: typeof PraxisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preise': {
      id: '/preise'
      path: '/preise'
      fullPath: '/preise'
      preLoaderRoute: typeof PreiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pruefung': {
      id: '/pruefung'
      path: '/pruefung'
      fullPath: '/pruefung'
      preLoaderRoute: typeof PruefungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risiken': {
      id: '/risiken'
      path: '/risiken'
      fullPath: '/risiken'
      preLoaderRoute: typeof RisikenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vorschau': {
      id: '/vorschau'
      path: '/vorschau'
      fullPath: '/vorschau'
      preLoaderRoute: typeof VorschauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widerruf': {
      id: '/widerruf'
      path: '/widerruf'
      fullPath: '/widerruf'
      preLoaderRoute: typeof WiderrufRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wissen': {
      id: '/wissen'
      path: '/wissen'
      fullPath: '/wissen'
      preLoaderRoute: typeof WissenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zahlung': {
      id: '/zahlung'
      path: '/zahlung'
      fullPath: '/zahlung'
      preLoaderRoute: typeof ZahlungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/akte/': {
      id: '/akte/'
      path: '/'
      fullPath: '/akte/'
      preLoaderRoute: typeof AkteIndexRouteImport
      parentRoute: typeof AkteRoute
    }
    '/akte/$id': {
      id: '/akte/$id'
      path: '/$id'
      fullPath: '/akte/$id'
      preLoaderRoute: typeof AkteIdRouteImport
      parentRoute: typeof AkteRoute
    }
    '/anbieter/': {
      id: '/anbieter/'
      path: '/'
      fullPath: '/anbieter/'
      preLoaderRoute: typeof AnbieterIndexRouteImport
      parentRoute: typeof AnbieterRoute
    }
    '/anbieter/$slug': {
      id: '/anbieter/$slug'
      path: '/$slug'
      fullPath: '/anbieter/$slug'
      preLoaderRoute: typeof AnbieterSlugRouteImport
      parentRoute: typeof AnbieterRoute
    }
    '/ergebnisse/': {
      id: '/ergebnisse/'
      path: '/'
      fullPath: '/ergebnisse/'
      preLoaderRoute: typeof ErgebnisseIndexRouteImport
      parentRoute: typeof ErgebnisseRoute
    }
    '/ergebnisse/$id': {
      id: '/ergebnisse/$id'
      path: '/$id'
      fullPath: '/ergebnisse/$id'
      preLoaderRoute: typeof ErgebnisseIdRouteImport
      parentRoute: typeof ErgebnisseRoute
    }
    '/ergebnisse/meine': {
      id: '/ergebnisse/meine'
      path: '/meine'
      fullPath: '/ergebnisse/meine'
      preLoaderRoute: typeof ErgebnisseMeineRouteImport
      parentRoute: typeof ErgebnisseRoute
    }
    '/ergebnisse/teilen': {
      id: '/ergebnisse/teilen'
      path: '/teilen'
      fullPath: '/ergebnisse/teilen'
      preLoaderRoute: typeof ErgebnisseTeilenRouteImport
      parentRoute: typeof ErgebnisseRoute
    }
    '/pro/abbruch': {
      id: '/pro/abbruch'
      path: '/abbruch'
      fullPath: '/pro/abbruch'
      preLoaderRoute: typeof ProAbbruchRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/erfolg': {
      id: '/pro/erfolg'
      path: '/erfolg'
      fullPath: '/pro/erfolg'
      preLoaderRoute: typeof ProErfolgRouteImport
      parentRoute: typeof ProRoute
    }
    '/wissen/': {
      id: '/wissen/'
      path: '/'
      fullPath: '/wissen/'
      preLoaderRoute: typeof WissenIndexRouteImport
      parentRoute: typeof WissenRoute
    }
    '/wissen/$slug': {
      id: '/wissen/$slug'
      path: '/$slug'
      fullPath: '/wissen/$slug'
      preLoaderRoute: typeof WissenSlugRouteImport
      parentRoute: typeof WissenRoute
    }
    '/zahlung/': {
      id: '/zahlung/'
      path: '/'
      fullPath: '/zahlung/'
      preLoaderRoute: typeof ZahlungIndexRouteImport
      parentRoute: typeof ZahlungRoute
    }
    '/zahlung/$id': {
      id: '/zahlung/$id'
      path: '/$id'
      fullPath: '/zahlung/$id'
      preLoaderRoute: typeof ZahlungIdRouteImport
      parentRoute: typeof ZahlungRoute
    }
    '/zahlung/abbruch': {
      id: '/zahlung/abbruch'
      path: '/abbruch'
      fullPath: '/zahlung/abbruch'
      preLoaderRoute: typeof ZahlungAbbruchRouteImport
      parentRoute: typeof ZahlungRoute
    }
    '/zahlung/erfolg': {
      id: '/zahlung/erfolg'
      path: '/erfolg'
      fullPath: '/zahlung/erfolg'
      preLoaderRoute: typeof ZahlungErfolgRouteImport
      parentRoute: typeof ZahlungRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stripe/webhook': {
      id: '/api/stripe/webhook'
      path: '/api/stripe/webhook'
      fullPath: '/api/stripe/webhook'
      preLoaderRoute: typeof ApiStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AkteRouteChildren {
  AkteIdRoute: typeof AkteIdRoute
  AkteIndexRoute: typeof AkteIndexRoute
}

const AkteRouteChildren: AkteRouteChildren = {
  AkteIdRoute: AkteIdRoute,
  AkteIndexRoute: AkteIndexRoute,
}

const AkteRouteWithChildren = AkteRoute._addFileChildren(AkteRouteChildren)

interface AnbieterRouteChildren {
  AnbieterSlugRoute: typeof AnbieterSlugRoute
  AnbieterIndexRoute: typeof AnbieterIndexRoute
}

const AnbieterRouteChildren: AnbieterRouteChildren = {
  AnbieterSlugRoute: AnbieterSlugRoute,
  AnbieterIndexRoute: AnbieterIndexRoute,
}

const AnbieterRouteWithChildren = AnbieterRoute._addFileChildren(
  AnbieterRouteChildren,
)

interface ErgebnisseRouteChildren {
  ErgebnisseIdRoute: typeof ErgebnisseIdRoute
  ErgebnisseMeineRoute: typeof ErgebnisseMeineRoute
  ErgebnisseTeilenRoute: typeof ErgebnisseTeilenRoute
  ErgebnisseIndexRoute: typeof ErgebnisseIndexRoute
}

const ErgebnisseRouteChildren: ErgebnisseRouteChildren = {
  ErgebnisseIdRoute: ErgebnisseIdRoute,
  ErgebnisseMeineRoute: ErgebnisseMeineRoute,
  ErgebnisseTeilenRoute: ErgebnisseTeilenRoute,
  ErgebnisseIndexRoute: ErgebnisseIndexRoute,
}

const ErgebnisseRouteWithChildren = ErgebnisseRoute._addFileChildren(
  ErgebnisseRouteChildren,
)

interface ProRouteChildren {
  ProAbbruchRoute: typeof ProAbbruchRoute
  ProErfolgRoute: typeof ProErfolgRoute
}

const ProRouteChildren: ProRouteChildren = {
  ProAbbruchRoute: ProAbbruchRoute,
  ProErfolgRoute: ProErfolgRoute,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

interface WissenRouteChildren {
  WissenSlugRoute: typeof WissenSlugRoute
  WissenIndexRoute: typeof WissenIndexRoute
}

const WissenRouteChildren: WissenRouteChildren = {
  WissenSlugRoute: WissenSlugRoute,
  WissenIndexRoute: WissenIndexRoute,
}

const WissenRouteWithChildren =
  WissenRoute._addFileChildren(WissenRouteChildren)

interface ZahlungRouteChildren {
  ZahlungIdRoute: typeof ZahlungIdRoute
  ZahlungAbbruchRoute: typeof ZahlungAbbruchRoute
  ZahlungErfolgRoute: typeof ZahlungErfolgRoute
  ZahlungIndexRoute: typeof ZahlungIndexRoute
}

const ZahlungRouteChildren: ZahlungRouteChildren = {
  ZahlungIdRoute: ZahlungIdRoute,
  ZahlungAbbruchRoute: ZahlungAbbruchRoute,
  ZahlungErfolgRoute: ZahlungErfolgRoute,
  ZahlungIndexRoute: ZahlungIndexRoute,
}

const ZahlungRouteWithChildren =
  ZahlungRoute._addFileChildren(ZahlungRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  AkteRoute: AkteRouteWithChildren,
  AnbieterRoute: AnbieterRouteWithChildren,
  AssistentRoute: AssistentRoute,
  BestaetigenRoute: BestaetigenRoute,
  CheckRoute: CheckRoute,
  ComplianceRoute: ComplianceRoute,
  DatenschutzRoute: DatenschutzRoute,
  EinwilligungenRoute: EinwilligungenRoute,
  ErgebnisRoute: ErgebnisRoute,
  ErgebnisseRoute: ErgebnisseRouteWithChildren,
  ErinnerungenRoute: ErinnerungenRoute,
  HinweiseRoute: HinweiseRoute,
  ImpressumRoute: ImpressumRoute,
  InstallierenRoute: InstallierenRoute,
  KaeufeRoute: KaeufeRoute,
  KoerperRoute: KoerperRoute,
  LoginRoute: LoginRoute,
  MehrRoute: MehrRoute,
  PlanerRoute: PlanerRoute,
  PraxisRoute: PraxisRoute,
  PreiseRoute: PreiseRoute,
  ProRoute: ProRouteWithChildren,
  PruefungRoute: PruefungRoute,
  RisikenRoute: RisikenRoute,
  ScannerRoute: ScannerRoute,
  VorschauRoute: VorschauRoute,
  WiderrufRoute: WiderrufRoute,
  WissenRoute: WissenRouteWithChildren,
  ZahlungRoute: ZahlungRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiStripeWebhookRoute: ApiStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
